on:
  workflow_dispatch:

name: Update binaries

jobs:
  update:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update package library
        run: ./update.sh

      - name: Commit R package library updates
        run: |
          git add .
          git status
          git config --global user.name 'Jeroen Ooms'
          git config --global user.email 'jeroenooms@gmail.com'
          git commit -m "Auto update binaries"
          git push
